[package]
name = "intake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sifter_proto = { path = "../sifter_proto" }
query_parser = { path = "../query_parser" }
chrono = "0.4.31"
uuid = "1.4.1"
